### ISSUE TITLE
BackgroundFetchClick event gives access to the request-response pairs.

### ISSUE THREAD

**Issue by mugdhalakhani** [WICG/background-fetch#105]
BackgroundFetchClickEvent has the registration attribute, which gives access to the request-response pairs from the background fetch via match() and matchAll(). This is problem if the click event is propagated after success of fail events (in response, say, to the user clicking on the notification, hours after the background fetch has finished), because we'd like to be able to move the downloaded data to the developer's private cache in response to success|fail events, instead of copying it.

If we can prevent access to the downloaded data through the click event after the fetch has finished, this moving will be possible, and also, the user agent can delete the data on their end once the processing of success|fail events has finished (or hit a timeout).

**Comment by beverloo** [comment]
We can extend this to _disallow use of `match` and `matchAll` once the Background Fetch has been settled_, i.e. after invocation of the `backgroundfetchsuccess`, `backgroundfetchfail` or `backgroundfetchabort` event in the Service Worker has finished.

**Comment by jakearchibald** [comment]
Fixed in e760d0980bbc317a688bf4ec098a71c04e223eb7
