### ISSUE TITLE
Better handling of temporary network failures

### ISSUE THREAD

**Issue by ewoerner** [WICG/background-fetch#111]
Currently, there are quite a few situations in which background fetch could fail even though the situations can actually be classified as temporary network failures. Examples:
* a stream becomes errored, however the operating system only classifies the network as offline a few minutes later
* a request fails with a certificate failure because of a captive portal

In these cases, it would be desirable from a user perspective if the download resumes at a later point in time.

**Comment by jakearchibald** [comment]
> a stream becomes errored, however the operating system only classifies the network as offline a few minutes later

I think the spec covers this case. "Wait until the user agent is not offline" doesn't require trusting the OS.

> a request fails with a certificate failure because of a captive portal

Good point. I'll change "If the user agent is offline" to something like "If the issue is judged to be temporary (eg, user is offline, user is behind a captive portal)…"
