### ISSUE TITLE
Typography: interface names need to be marked up as code

### ISSUE THREAD

**Issue by annevk** [WICG/background-fetch#120]
E.g., `BackgroundFetchEvent`, not BackgroundFetchEvent.

**Comment by jakearchibald** [comment]
Every `BackgroundFetchEvent` I can see is in `<code class="idl">`.

**Comment by annevk** [comment]
Sorry, I misinspected. I guess W3C styling threw me off.

**Comment by annevk** [comment]
I'm gonna reopen this for a bit, since I think this does hurt readability quite a bit. E.g., step 2.4 of https://wicg.github.io/background-fetch/#create-record-objects says "Headers" twice, but the first time it's a field (which arguably has to be spelled with a lowercase "h" but we don't have it formalized) and the second time it's an object. It's really hard to tell these apart visually.

**Comment by jakearchibald** [comment]
I'll do something locally & recommend it for upstreaming.

> which arguably has to be spelled with a lowercase "h" but we don't have it formalized

Ohh I didn't know these were case sensitive.
