### ISSUE TITLE
"Let request be a copy of record’s request."

### ISSUE THREAD

**Issue by annevk** [WICG/background-fetch#121]
This isn't that easy, if request holds onto a stream, right?

**Comment by jakearchibald** [comment]
The stream is read to storage in http://localhost:8080/background-fetch/#background-fetch-manager-fetch 8.8.3.1.1

**Comment by annevk** [comment]
I see. It might be worth adding another note here, perhaps, but maybe this is okay.

In general I think we need to be more precise when we say "copy/clone", but that's endemic.

**Comment by jakearchibald** [comment]
Agreed.
