### ISSUE TITLE
Typo in the "failureReason"

### ISSUE THREAD

**Issue by armelpingault** [WICG/background-fetch#132]
I believe there is a little typo in the `failureReason`. While I was testing this new feature, I noticed that when I was setting the wrong `downloadTotal` to throw a download exceeed error, the words `total` and `download` were actually inverted. For example:
```
const bgFetch = await swReg.backgroundFetch.fetch('my-fetch', ['/ep-5.mp3', 'ep-5-artwork.jpg'], {
    title: 'Episode 5: Interesting things.',
    icons: [{
      sizes: '300x300',
      src: '/ep-5-icon.png',
      type: 'image/png',
    }],
    downloadTotal: 1,
  });
}
console.log(bgFetch);
```
I am getting a:
```
failureReason: "total-download-exceeded"
```
However the documentation is mentioning:
```
"download-total-exceeded" - The provided `downloadTotal` was exceeded.
```

**Comment by jakearchibald** [comment]
This smells like a Chrome bug to me. Thanks for spotting it.

**Comment by jakearchibald** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=913867.
