### ISSUE TITLE
Current support of background fetch

### ISSUE THREAD

**Issue by scailbc** [WICG/background-fetch#141]
Hello, I've tried to run some sample projects with background fetch but it doesn't seems to work, even the [sample project bgfetch-http203](https://bgfetch-http203.glitch.me/) described [here](https://youtu.be/cElAoxhQz6w) doesn't work. I've tried on Windows 10 with:
- Google Chrome Version 79.0.3945.88 (Official Build) (64 bit)
- Google Chrome Version 80.0.3987.16 (Official Build) beta ( 64 bit)
- Google Chrome Version 81.0.4006.0 (Official Build) canary (64-bit)

Even by enabling _Experimental Web Platform features_ flag I couldn't make it work.

Online I couldn't find any news or docs about this feature, except for some artcles in 2017 and 2018.

What is the current status of BackgroundFetch? Which browsers/OS supports it? Do I have to enable some settings?

**Comment by jakearchibald** [comment]
Can you file an issue on crbug.com?

**Comment by OrenMe** [comment]
@scailbc can you please link back the bug here, would like to follow it as well.
