### ISSUE TITLE
[CHROME ANDROID] responseReady still pending, no progression, upload locked

### ISSUE THREAD

**Issue by arezkisaba** [WICG/background-fetch#149]
Hello,
I've this problem on CHROME ANDROID, when i use the background fetch, the download progress displayed by the browser is still 0%, it's blocked, even for a very very small file.
It works on CHROME WINDOWS.

Android version : 9
Build number : PPIS29.65-24-2

**Comment by jakearchibald** [comment]
Please file an issue with a minimal reproduction on crbug.com.
