### ISSUE TITLE
Coalesce or defer SW events 

### ISSUE THREAD

**Issue by owencm** [WICG/background-fetch#2]
**Summary**: I suspect we need a way to minimize the number of events fired into the SW if the site is downloading files in chunks. I suspect we also want to be able to defer the events for some time.

Observations:
- Often these downloads/uploads will be occurring in the background on low memory devices 
- On such devices it may be difficult to wake up a SW in the background, or keep a renderer alive
- Some sites may want to download many files (e.g. songs for an album) or chunk files and download them individually (e.g. parts of a movie).

I'm presuming that the current design coalesces all files downloaded in one call to the API into one event fired in the SW, is that correct? If not I think we need to support some form of coalescing.

Do you see any issues with a browser deferring the events until it is next opened in the foreground to maximize the chance of success on low memory devices?

Thanks

**Comment by jakearchibald** [comment]
We only fire one event per background fetch grouping.
