### ISSUE TITLE
Should BackgroundFetchRegistration.abort() return a Promise?

### ISSUE THREAD

**Issue by beverloo** [WICG/background-fetch#31]
Since only a single registration for a {service worker registration, _tag_} pair may be active at a time, having `abort()` return a void Promise will enable developers to avoid a race condition when having to re-register a background fetch with the same _tag_.

**Comment by jakearchibald** [comment]
Yeah, this makes sense. Maybe even return a boolean to indicate whether it aborted.

**Comment by beverloo** [comment]
Counter: `Notification.close()` returns nothing. It'd be cool if we can align the specs, even if it's not always equally useful.

/cc @annevk

**Comment by jakearchibald** [comment]
Kinda related: JS `map.delete(key)` returns a boolean indicating if an item was actually removed. We copies this in the cache API (but with promises).
