### ISSUE TITLE
Naming of BackgroundFetch(Active,Settled)Fetches

### ISSUE THREAD

**Issue by beverloo** [WICG/background-fetch#32]
https://wicg.github.io/background-fetch/#background-fetch-registration

A `BackgroundFetchRegistration` has a sequence of active _fetches_, whereas two events have a sequence of settled _fetches_. Each entry in such a sequence, of type `BackgroundFetchFetches`, contains a single request/response(Ready) pair, while the name implies its multiple.

Could we consider renaming them as follows?

Current | Proposed
------------ | -------------
BackgroundFetchFetches | BackgroundFetchRequest
BackgroundFetchActiveFetches | BackgroundFetchActiveRequest
BackgroundFetchSettledFetches | BackgroundFetchSettledRequest

One concern here is that they _describe_ and contain a request, as opposed to being an actual request. We can stick `Info` in the name too, but that makes the types even longer. WDYT?

**Comment by jakearchibald** [comment]
It absolutely shouldn't be plural, but I don't think `Request` is right, since it isn't a `Request` object. Going to remove the plural bit.
