### ISSUE TITLE
Fail on 404?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/background-fetch#4]
We made a big mistake with `cache.addAll` by considering 404 etc successful. We changed it so 404 is considered a failure. However, this means it can't be used for opaque resources, until we decide that `response.ok` already leaks for opaque responses by other means (`<object>`), and expose it.

Personally I'm flip-flopping on this, and think it could be dependent on the outcome of https://github.com/jakearchibald/background-cache/issues/3.

**Comment by jakearchibald** [comment]
If the user wants to fail on 404, this allows us to abort the other fetches in the operation early.

If the user doesn't want to fail on 404, they can inspect the resulting request/response map and check if they're all ok, and decide themselves if the failed item(s) aren't that much of a big deal, and cache the others anyway.

**Comment by jakearchibald** [comment]
If an upload fails, the reason for failure is often interesting. Eg, is it a terminal or temporary failure? If we do fail on `response.ok`, we should have an option to reverse that.

**Comment by ShaneHudson** [comment]
Could you leave this up to the user? In same way on a browser's downloads you have cancel and retry. If the download appears in the user's notifications then they can choose.

**Comment by jakearchibald** [comment]
Yeah an option is probably enough

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/background-fetch/commit/52bf7437807d2b540697d35f7f5002c09543315d

**Comment by jakearchibald** [comment]
Ughghgh I keep changing my mind on this. It probably shouldn't fail on 404 etc, because fetch doesn't, and this is background "fetch".

**Comment by jakearchibald** [comment]
Responses with a `!ok` status code will still be considered complete fetches.

We can add an option later to change the behaviour if developers find it awkward.
