### ISSUE TITLE
please, update url!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [WICG/background-fetch#59]
https://wicg.github.io/background-fetch/

<del>https://jakearchibald.github.io/background-fetch</del>

**Comment by jakearchibald** [comment]
Where are you seeing the old URL?

**Comment by jakearchibald** [comment]
Found it! https://github.com/WICG/background-fetch/commit/1bb8484de9a56ef0bfdc5174e178fc0261f2b5a6
