### ISSUE TITLE
Fail if more bytes are downloaded than downloadSize

### ISSUE THREAD

**Issue by jakearchibald** [WICG/background-fetch#63]
This ensures what looks like a 100k download doesn't become a 100mb download without the user knowing about it.

**Comment by jakearchibald** [comment]
It should be ok if the total download is less than `downloadSize`. If the developer is unsure of the total, they can provide a conservative estimate.

**Comment by mugdhalakhani** [comment]
+1. This also incentivizes developers to think about a downloadTotal and add a padding to it if they think the underlying content will change slightly after the fetch() has started. Which is something we should probably mention in the spec.

**Comment by jakearchibald** [comment]
There's a potential gotcha here, that the developer:

* Sets 1000 resources to background fetch, and sets a `downloadSize` that is accurate.
* By the time the browser gets round to fetching the 1000th item, it's changed, increasing in size by one byte.
* The background fetch fails.

This is the kind of bug that's unlikely to show in dev.

As a solution, the developer could either pad `downloadSize`, or the browser could grant some leeway, eg allow the download to be n% larger than specified.

Padding `downloadSize` could disrupt progress bars, depending on the amount of padding, so maybe leeway is a better solution.

**Comment by jakearchibald** [comment]
Done! Will add docs for the padding details.
