### ISSUE TITLE
Make getIDs() return a promise for a sequence

### ISSUE THREAD

**Issue by annevk** [WICG/background-fetch#68]
This doesn't seem like a thing that warrants a frozen array. A normal array is fine.

**Comment by jakearchibald** [comment]
I thought we avoided returning sequences. Did that change or did I misunderstand?

**Comment by annevk** [comment]
Only for property getters because we want obj.x === obj.x and folks didn't like that to be a modified array. However, for methods sequences are the way to go.

**Comment by jakearchibald** [comment]
Done!
