### ISSUE TITLE
BackgroundFetchEvent constructor

### ISSUE THREAD

**Issue by annevk** [WICG/background-fetch#69]
You shouldn't have to define this as the DOM Standard defines a generic one.

**Comment by jakearchibald** [comment]
Interesting, how does this work given the constructor takes non-generic arguments (the init arg)?

**Comment by annevk** [comment]
Does https://dom.spec.whatwg.org/#concept-event-constructor help? Ideally "Constructor" in the IDL directly links there. That's https://github.com/whatwg/dom/issues/604.

**Comment by jakearchibald** [comment]
Additionally, do I need to provide prose for the attributes, or is it assumed that it'll be "the value it was initialized to"?

**Comment by annevk** [comment]
Yes, the IDL needs to be complete. And yes, you'll need to provide prose for the attributes, at least until https://github.com/heycam/webidl/issues/258 is resolved, which depending on the resolution might allow for leaving all of that to IDL.

**Comment by jakearchibald** [comment]
Cheers. I'm going to copy what XHR does, which keeps it pretty light https://xhr.spec.whatwg.org/#dom-progressevent-lengthcomputable.

**Comment by jakearchibald** [comment]
Done!
