### ISSUE TITLE
Inconsistency with namespacing in names

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#71]
In response to https://github.com/w3ctag/design-reviews/issues/279

Events are namespaced with `backgroundfetch`, ie. `backgroundfetchfail` and `backgroundfetchabort`, but not `backgroundfetched` (which I assume is also called for completed uploads?)

There is also the inconsistency between fetchED and abort(no -ed) and fail (no -ed).

Maybe `backgroundfetchcomplete`?

**Comment by jakearchibald** [comment]
I agree there's an inconsistency here. `backgroundfetchcomplete` seems reasonable.

**Comment by slightlyoff** [comment]
Looks like this name change hasn't happened? Is that still planned?

**Comment by jakearchibald** [comment]
Fixed in 8b1f39c391222242ea3687739536986f7a5b37b3. I went with `backgroundfetchsuccess`.
