### ISSUE TITLE
`backgroundfetchclick`, what am I clicking on

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#72]
In response to https://github.com/w3ctag/design-reviews/issues/279

It feels a bit weird that you can click on a `backgroundfetch` which is an abstract things.

Other parts of the API has functions like `updateUI()` - so there is some inconsistency here.

Idea? Maybe make a `backgroundfetchuseraction` or similar instead. That could then also capture user aborts.

I do understand that this is modelled after `notificationclick` but there I think the context is much more clear, as a notification is also a user visible thing you can interact with. Maybe you can think of the UI as being a kind of notification and actually just name it `backgroundfetchnotificationclick`

**Comment by kenchris** [comment]
Yes, I noticed that, but mostly the name it is tied with something you can actually physically click on, like `notificationclick` - `backgroundfetch` is really abstract if you don't involve a word defining the UI component you are physically clicking on

**Comment by jakearchibald** [comment]
Doesn't https://wicg.github.io/background-fetch/#background-fetch-display clear it up? (especially once the TODOs are done)

**Comment by jakearchibald** [comment]
Closing this. Feel free to reopen.
