### ISSUE TITLE
updateUI - hard to know what UI it refers to

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#73]
In response to https://github.com/w3ctag/design-reviews/issues/279

`updateUI` sets the title which can be visible in some UI, maybe just call it `updateUserVisibleTitle`, `updateTitle` or similar?

**Comment by jakearchibald** [comment]
I'm going to write a (deliberately vague) "Display a background fetch" algorithm which should clear this up.

**Comment by jakearchibald** [comment]
This is also discussed in #79, and there's a PR https://github.com/WICG/background-fetch/pull/108
