### ISSUE TITLE
if downloadTotal is a hint, maybe add Hint to the name?

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#78]
In response to https://github.com/w3ctag/design-reviews/issues/279

`downloadTotalHint` vs `expectedDownloadTotalBytes` ?

**Comment by jakearchibald** [comment]
It isn't really a hint anymore, as we'll stop the download if it exceeds the `downloadTotal`. I need to update the explainer for this.

**Comment by kenchris** [comment]
`maxDownloadSize` ?

**Comment by jakearchibald** [comment]
Yeah, I like that.

**Comment by jakearchibald** [comment]
I think we need to stay away from "download" in this, since it's the total size of the response bodies. "download" seems to suggest bytes down the wire, which is different.

**Comment by jakearchibald** [comment]
Dupe of #66
