### ISSUE TITLE
The name fetch feels so weird when uploading

### ISSUE THREAD

**Issue by kenchris** [WICG/background-fetch#80]
For instance in the below example. But I guess that is also an issue with regular `fetch`

```
  const request = new Request('/upload-video', { body, method: 'POST' });

  const reg = await navigator.serviceWorker.ready;

  try {
    await reg.backgroundFetch.fetch(id, request, {
      title: "Uploading video"
    });
  }
```

**Comment by jakearchibald** [comment]
All fetches have an upload and download component. I don't think we should change naming here.

**Comment by kenchris** [comment]
Yeah that is my worry. Really bad name though given the definition for fetch

https://www.merriam-webster.com/dictionary/fetch
> to go or come after and bring or take back

**Comment by jakearchibald** [comment]
Yeah, I think this may trip folks up if they haven't already encountered it with `fetch()`. Going to close this since it's more of a general fetch problem. Reopen if you think we should break continuity with `fetch()`.
