### ISSUE TITLE
Many `matchAll`s. Consolidate?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/background-fetch#94]
We currently have three `match` and `matchAll` definitions

https://wicg.github.io/background-fetch/#background-fetch-registration
https://wicg.github.io/background-fetch/#background-fetch-settled-matching
https://wicg.github.io/background-fetch/#background-fetch-success-event

There are three because they each return a slightly different type, depending on when they're callable.

`bgFetchReg.matchAll()`. The bg fetch is still in progress, but we want to enable access to partial downloads (eg, listen to podcast while downloading). Here the return type is:

```ts
interface BackgroundFetchActiveFetch {
  request: Request;
  responseReady: Promise<Response>;
};
```

The request is always present, but the response may not have been received yet. It may also fail, resulting in rejection.

`fetchFailEvent.matchAll()` and `fetchAbortEvent.matchAll()`. Here the bg fetch has ended, but some of the responses may not have succeeded or completed. Some of the responses may not have an ok status.

```ts
interface BackgroundFetchSettledFetch {
  request: Request;
  response?: Response;
}; 
```

`fetchSuccessEvent.matchAll()`. Here the bg fetch has ended and every request will have a complete and successful response.

```ts
interface BackgroundFetchSuccessfulFetch {
  request: Request;
  response: Response;
}; 
```

I tried to make the type system as accurate as possible to make developer's lives easier:

* Avoid promises where they aren't needed.
* Avoid potentially undefined types when they won't be undefined. This is more of an issue with things like Flow/TypeScript.

The alternative is using `BackgroundFetchActiveFetch` for all definitions.

**Adding all fetched items to a cache**

Current API:

```js
const fetches = event.matchAll();
const promises = fetches.map(({request, response}) => {
  return cache.put(request, response);
});
await Promise.all(promises);
```

Single-definition API:

```js
const fetches = event.matchAll();
const promises = fetches.map(await ({request, responseReady}) => {
  return cache.put(request, await responseReady);
});
await Promise.all(promises);
```

Here, the difference isn't that big. So single-definition looks fine.

**Adding all successful items to a cache as part of a failed bgfetch**

Some of the items may have failed, but I want to add the ones that worked to a cache.

Current API:

```js
const fetches = event.matchAll();
const promises = fetches.map(({request, response}) => {
  if (!response || !response.ok) return;
  return cache.put(request, response);
});
await Promise.all(promises);
```

Single-definition API:

```js
const fetches = event.matchAll();
const promises = fetches.map(async ({request, responseReady}) => {
  try {
    const response = await responseReady;
    if (!response.ok) return;
    return cache.put(request, response);
  } catch (error) {}
});
await Promise.all(promises);
```

This is a little worse, but maybe bearable since it isn't a the common case? We could also add things in future to make this easier, like `matchAll({ successfulOnly: true })`.

It's also worth noting that developers could create a filter like this themselves.

```js
async function successfulRecords(records) {
  const promises = Promise.all(
    records.map(async ({request, responseReady}) => {
      try {
        const response = await responseReady;
        if (!response.ok) return;
        return { request, response };
      } catch (error) {}
    })
  );

  return (await promises).filter(v => v);
}
```

**Comment by jakearchibald** [comment]
+@beverloo @mugdhalakhani

(@domenic this is the issue we spoke about on Friday)

**Comment by domenic** [comment]
Glad things worked out. My only note for the future is that I would caution against splitting interfaces so that you can make a return type nullable/non-nullable. Remember that splitting interfaces causes new implementation code to be generated, and that return types are just documentation. It is OK to have slightly-broader-than-necessary return types if it makes a class more useful.

If the concern is on the level of tooling like TypeScript, the tooling should be updated, not the spec.

**Comment by jakearchibald** [comment]
Done!
